# Generated by Django 6.0.4 on 2026-05-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printjob',
            options={'verbose_name': 'Виробниче завдання', 'verbose_name_plural': 'Виробничі завдання'},
        ),
        migrations.AddField(
            model_name='printjob',
            name='binding_type',
            field=models.CharField(blank=True, choices=[('perfect', 'Клейове скріплення (КБС)'), ('thread', 'Ниткове зшивання'), ('staple', 'Скобка (брошурування)'), ('hardcover', 'Тверда палітурка')], max_length=20, verbose_name='Тип скріплення'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='circulation',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Тираж (прим.)'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='format',
            field=models.CharField(blank=True, help_text='Наприклад: 60×84/16, 70×100/16', max_length=20, verbose_name='Формат видання'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='paper_type',
            field=models.CharField(blank=True, choices=[('offset_80', 'Офсетний 80 г/м²'), ('offset_120', 'Офсетний 120 г/м²'), ('coated_130', 'Крейдований 130 г/м²'), ('coated_170', 'Крейдований 170 г/м²')], max_length=20, verbose_name='Тип паперу'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='print_method',
            field=models.CharField(blank=True, choices=[('offset', 'Офсетний друк'), ('digital', 'Цифровий друк'), ('risograph', 'Ризографія')], max_length=20, verbose_name='Спосіб друку'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершення виробництва'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Виробничі примітки'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Початок виробництва'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('prepress', 'Додрукарська підготовка'), ('printing', 'Друк'), ('postpress', 'Післядрукарська обробка'), ('done', 'Виконано')], default='pending', max_length=20, verbose_name='Статус виробництва'),
        ),
    ]
